#!/usr/bin/env python3
"""Embed the fixed presentation bundle; never map a request to a filesystem path."""

import argparse
from pathlib import Path

ASSET_FILES = {
    "index.html": "text/html",
    "app.css": "text/css",
    "app.js": "text/javascript",
    "bridge.js": "text/javascript",
}
MAX_ASSET_BYTES = 1024 * 1024


def render_header(asset_directory: Path) -> str:
    declarations = []
    entries = []
    for index, (name, mime_type) in enumerate(sorted(ASSET_FILES.items())):
        path = asset_directory / name
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"Expected a regular bundled asset: {path}")
        content = path.read_bytes()
        if not content or len(content) > MAX_ASSET_BYTES:
            raise ValueError(f"Asset must contain 1..{MAX_ASSET_BYTES} bytes: {name}")
        content.decode("utf-8")  # Reject accidental binary or invalid text assets.
        values = [
            "  " + ", ".join(f"0x{byte:02x}" for byte in content[offset : offset + 16])
            for offset in range(0, len(content), 16)
        ]
        declarations.append(
            f"inline const unsigned char kAsset{index}[] = {{\n"
            + ",\n".join(values)
            + "\n};"
        )
        entries.append(
            f'  {{"{name}", "{mime_type}", '
            f"std::string_view(reinterpret_cast<const char*>(kAsset{index}), "
            f"sizeof(kAsset{index}))}}"
        )
    return (
        "// Generated by tools/embed_assets.py. Do not edit.\n"
        "#ifndef KUNLUN_DESKTOP_GENERATED_ASSETS_H_\n"
        "#define KUNLUN_DESKTOP_GENERATED_ASSETS_H_\n"
        '#include "host/asset.h"\n'
        "#include <array>\n"
        "namespace kunlun {\n"
        + "\n".join(declarations)
        + f"\ninline const std::array<Asset, {len(entries)}> kAssets = {{{{\n"
        + ",\n".join(entries)
        + "\n}};\n"
        "}  // namespace kunlun\n"
        "#endif\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--assets", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    arguments = parser.parse_args()
    header = render_header(arguments.assets)
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    if not arguments.output.exists() or arguments.output.read_text() != header:
        arguments.output.write_text(header, encoding="utf-8")


if __name__ == "__main__":
    main()
